### ISSUE TITLE
Pip complains for me when cross compiling.

### ISSUE THREAD

**Issue by oridb** [benfogle/crossenv#1] opened 2018-07-20 23:59 UTC
Hi,

First off, this tool looks very promising. However, I've run into a few issues. First off,

     (cross) ; pip install -v numpy
     Traceback (most recent call last):
      File "/home/ori/src/py/xcenv/cross/bin/pip", line 7, in <module>
         from pip._internal import main
     ModuleNotFoundError: No module named 'pip._internal'

I can use pip as a module to make this work:

       python -m pip install -v numpy

I'm using Debian, with a self-built Python 3.6. I'm trying to cross compile for Android API 23 (I've added some minor patches to get nl_langinfo to work.)

**Comment by benfogle** [comment] 2018-07-21 01:53
It looks like the issue is that build-pip is version 9 and cross-pip is version 10, and somehow it's pulling in the wrong packages. I'm working on a fix for this now.

**Comment by benfogle** [comment] 2018-07-21 03:57
Tests are passing. Closing.

**Closed by benfogle** 2018-07-21 03:57 UTC
